### PR TITLE
Convert repo to use Go Modules, fix compilation issues

### PR DESCRIPTION
**Pull request by richscott**
This set of changes basically converts the repository from using the old `gb` command (which is long deprecated) for building and testing to using contemporary Go modules. Several folks weren't able to compile the prior revision, getting the following error:
```
runtime.main_main·f: function main is undeclared in the main package
# github.com/mickep76/etcdtool
github.com/mickep76/etcdtool
FATAL: command "build" failed: exit status 2
make: *** [build] Error 1
```
This change removes the `vendor/` libraries directory, and uses Go Modules that are dynamically fetched (upon initial build), which are stored in the user's  `$GOPATH/pkg/mod` (the usual Go module storage cache path).  An initial `go.mod` was created, using the same packages and their versions as was previously in the `vendor/` dir.  The code now compiles and saves output to `build/`, and the Makefile has been updated with the new path.

The building and basic testing was done with Go 1.14.2, on a Macbook running macOS 10.5.4. I haven't done extensive testing with the resultant binary, but coworkers tell me it appears to function just as older binaries once did (they are not experienced Go devs and asked me to help them get this to compile). I hope this is helpful to anyone who wants to build and use this.

### CODE REVIEW

**Comment by richscott** [comment]
Also, I haven't done any testing with the Makefile targets for building RPM or Brew packages, as I have no experience in developing those.

**Comment by mickep76** [comment]
Thank's for doing this!

I haven't really worked on this in a long time, since I thought nobody was really using it since Etcd v3 does away with a nested key / value pairs and opted for a flat one.

I'd be interested in hearing what you still use it for?

I'll merge this since even untested it improves it from non-working to working ;D

**Comment by richscott** [comment]
Well, I don't use etc directly - I just work on REST-based microservices written in Go. However, other team(s) at my employer still have etcd v2 running, and use it for dynamic inventory tracking with Ansible. I suspect etcd will be replaced with something else, but etcdtool will be useful for dumping configurations to migrate to a new system.

**Comment by mickep76** [comment]
Nice Go is great for REST or gRPC, started using gRPC a few years ago it's really amazing.

It's kinda ironic it's used to migrate away from Etcd v2 ;D

But always nice that someone finds it useful.

**Pull request merged**
