### PR TITLE
Added detail to output of validate command

### PR DESCRIPTION
**Pull request by davewalk**
I know this is a very small thing but as a new user of this project and JSON schema in general this would've saved me some time today figuring out what was going on with my schema.

### CODE REVIEW

**Comment by davewalk** [comment]
btw this tool has been :100:   for us so far

**Comment by mickep76** [comment]
Cool, I wrote it for my own needs glad to hear someone else finds it useful. I'll have a look at this l8r today and merge it.

**Comment by mickep76** [comment]
I would consider adjusting the value output to the format being used like json/toml/yaml, I think it would be more readable for someone who doesn't understand Go(lang)?

**Comment by mickep76** [comment]
I would make it the default behavior, but add a switch for disabling it like --no-values, since it might generate quite a lot of output.

**Comment by davewalk** [comment]
I was going to make the changes that you suggested, just hadn't gotten to it yet - I'll send another PR soon

**Comment by mickep76** [comment]
No worries this one works soo I'll just merge it when you have it.

**Pull request merged**
